config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :line_items
  resources :unit_types
  resources :categories
  resources :products
  resources :orders, only: [:new, :create]
  get '/carts:id', to: 'carts#show'
  get '/carts/current', to: 'carts#showcurrent'
  delete 'carts/:cart_id/line_items/:id', to: 'line_items#destroy', as: 'cart_line_item'
  post 'create_new_cart', to: 'carts#create_new_cart', as: 'create_new_cart'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show_current show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def showcurrent
    @cart = current_cart
  end

  def create_new_cart
    session[:cart_id] = nil
    redirect_to new_cart_path
  end

  def show
    @cart = Cart.find(params[:id])
    session[:cart_id] = @cart.id
  end

  def current_cart
    @current_cart ||= Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
    @current_cart
  end
  # GET /carts/new
  def new
    @cart = Cart.new

  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        session[:cart_id] = @cart.id # przypisz id nowo utworzonego koszyka do sesji
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="margin: 20px">
    <%= form.submit class: 'btn-add' %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Koszyk</h1> <br />

<%= button_to "New cart", create_new_cart_path, class: 'btn-add', method: :post %> <br />

<div id="categories">
  <table id="customers">
    <thead>
    <tr>
      <th>Nazwa</th>
    </tr>
    </thead>
    <tfoot>


  <% @carts.each do |cart| %>
    <%= render cart %>
      <tr>
        <td> <%= link_to "Zobacz koszyk ##{cart.id}", cart %></td>
      </tr>
  <% end %>

    </tfoot>
  </table>
</div>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>


<h1>Koszyk</h1><br />

<% if @cart.line_items.empty? %>
  <p>Koszyk jest pusty!</p>
<% else %>
  <table id="customers">
    <thead>
    <tr>
      <th>Nazwa</th>
      <th>Cena za jeden produkt</th>
      <th>Ilosc</th>
      <th>Cena za calosc</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @cart.line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product.name %></td>
        <td><%= number_to_currency(line_item.price) %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.total_price %></td>
        <td><%= button_to 'Remove',  cart_line_item_path(@cart, line_item), method: :delete, class: 'btn-add' %></td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td><b>Total:</b></td>
      <td><b><%= @cart.total_price %></b></td>
      <td></td>
    </tr>
    </tfoot>
  </table>

<% end %>


<div><br />
  <%= link_to "Back to carts", carts_path %>
<br />
<br />
  <%= button_to "Destroy this cart",  @cart, method: :delete, class: 'btn-add'%>
</div>