config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :line_items
  resources :unit_types
  resources :categories
  resources :products
  resources :orders, only: [:new, :create]
  get '/carts:id', to: 'carts#show'
  get '/carts/current', to: 'carts#showcurrent'
  delete 'carts/:cart_id/line_items/:id', to: 'line_items#destroy', as: 'cart_line_item'
  post 'create_new_cart', to: 'carts#create_new_cart', as: 'create_new_cart'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    price.to_i * quantity.to_i.to_d
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  def current_cart
    if session[:cart_id]
      Cart.find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
      cart
    end
  end
  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  # def create
  #   @line_item = LineItem.new(line_item_params)
  #
  #   respond_to do |format|
  #     if @line_item.save
  #       format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully created." }
  #       format.json { render :show, status: :created, location: @line_item }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @line_item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def create
    if params[:cart_id]
      @cart = Cart.find(params[:cart_id])
    else
      @cart = current_cart
    end

    @line_item = @cart.line_items.build(line_item_params)
    @product = Product.find(line_item_params[:product_id])
    @line_item.price = @product.price
    @line_item.product = @product

    if @line_item.save
      redirect_to @cart, notice: 'Line item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_items_path, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @cart = current_cart
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    session[:cart_id] = nil
    redirect_to cart_path(@cart), notice: 'Line item was successfully removed from cart.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id, :quantity, :price)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.collection_select :product_id, Product.all, :id, :name, { prompt: true }, { selected: line_item.product_id } %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.collection_select :cart_id, Cart.all, :id, :id, { prompt: true }, { selected: line_item.cart_id } %>

  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div style="margin: 20px">
    <%= form.submit class: 'btn-add' %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr id="<%= dom_id line_item %>">
  <td><%= line_item.product.name %></td>
  <td><%= line_item.cart_id %></td>
  <td> <%= line_item.quantity %></td>
  <td> <%= line_item.price %></td>
  <td><%= link_to "Edytuj", { controller: 'line_items', action: 'edit', id: line_item.id } %></td>
  <td><%= button_to 'Usuń', cart_line_item_path(line_item.cart, line_item), method: :delete %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1> <br /><br />
<%= link_to "New line item", new_line_item_path %><br /><br />
<div id="categories">
  <table id="customers">
    <thead>
    <tr>
      <th>Nazwa</th>
      <th>Koszyk id</th>
      <th>Ilosc</th>
      <th>Cena</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tfoot>


  <% @line_items.each do |line_item| %>
    <%= render line_item %>
  <% end %>
    </tfoot>
  </table>
</div>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>