config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :line_items
  resources :unit_types
  resources :categories
  resources :products
  resources :orders, only: [:new, :create]
  get '/carts:id', to: 'carts#show'
  get '/carts/current', to: 'carts#showcurrent'
  delete 'carts/:cart_id/line_items/:id', to: 'line_items#destroy', as: 'cart_line_item'
  post 'create_new_cart', to: 'carts#create_new_cart', as: 'create_new_cart'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit&display=swap" rel="stylesheet">
  </head>

  <body>

  <div class="page">
    <nav class="navbar">
      <ul>
        <li class="menu"><%= link_to "Products", products_path %></li>
        <li class="menu"><%= link_to "Categories", categories_path %></li>
        <li class="menu"><%= link_to "Carts", carts_path %></li>
        <li class="menu"><%= link_to "Line Items", line_items_path %></li>
      </ul>
    </nav>

    <%= yield %>

  </div>


  </body>
</html>